---
abstract: 'Term::VT102 but with zero-based indices'
author:
  - 'Wrapper by Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-VT102-ZeroBased
no_index:
  directory:
    - inc
    - t
requires:
  Term::VT102: 0
resources:
  homepage: http://github.com/sartak/Term-VT102-ZeroBased/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/Term-VT102-ZeroBased.git
version: 1.02
